### ISSUE TITLE
remote video and remote audio muting not triggering events

### ISSUE THREAD

**Issue by Popl7** [ciscospark/spark-js-sdk#331]
When the remote party mutes his/her video or audio locally the locus.participant_video_muted and locus.participant_audio_muted events are trigggered.
The change:receivingVideo and change:receivingAudio events are not triggered.

This way it is not possible to detect that the remote party has muted his/her video or audio.

**Comment by ianwremmel** [comment]
Hi @Popl7. The calling features of the sdk are still in beta. in particular, event propagation isn't finished yet. I'll be focused on calling again soon, but with the holidays coming up, I don't have a good estimate on when that work will get finished.

**Comment by Popl7** [comment]
I understand.
Hopefully you can find time to add this.
With our beta testing muting is something we would like to offer, but the experience is not nice without these callbacks.

**Comment by ianwremmel** [comment]
hi @Popl7, this should be fixed in the general case. There are some backend issues that need to be resolved for some edge cases that should be taken care of in the next few weeks without any additional code changes. I'm going to close this for now, but if you still run into problems, please open a new ticket and we'll get them taken care of.
