### ISSUE TITLE
TypeError: Property 'authorization' must be of type state.

### ISSUE THREAD

**Issue by antoinelyset** [ciscospark/spark-js-sdk#409]
Hi, I'm using the `ciscospark.init()` (in a browser) to set programatically the `clientId`, `clientSecret`. I know you should build the browser version with ENV_VARS but it is not very practical for us. We want to set those infos at Runtime.

If I kickoff the OAuth flow with `ciscospark.authorize()`, it works. I get a nice json in my localStorage at the key `ciscospark`.

But then if I call `ciscospark.authorize()` again I have an error `Unhandled promise rejection TypeError: Property 'authorization' must be of type state. Tried to set [object Object]`.

Do you have any clue on what is happening ? What can I do ? Thanks.

Example of init : 

```javascript
const ciscospark = Ciscospark.init({
  config: {
    credentials: {
      oauth: {
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uri: redirectUri,
        scope,
      },
    },
  },
});
```

**Comment by ianwremmel** [comment]
ok, so, i've had my coffee now and I remember why init won't work in the browser. after doing an oauth login, as ciscospark instantiates, it checks window.location for an OAuth Authorization Code. ciscospark.init creates a *second* instance and that instance will never see the code in the url, since the first instance already used and removed it.

When you say you're calling ciscospark.authorize again, do you mean after an oauth redirect? or multiple times after a given page reload?

**Comment by antoinelyset** [comment]
I think it kind of works for the OAuth workflow, I can see the access_token (but no refresh_token) in the localStorage at the key "ciscospark". 

Yes I call #authorize before making a call. So after the OAuth and multiple times per page reload. I thought it was a simple call to test you're authenticated and proceed to a call. Isn't it ?

**Comment by ianwremmel** [comment]
ok, yea, the oauth flow might work now that the sdk handles localstorage, but it's only working because because both ciscospark instances talk to the same local storage key. I imagine that could produce race conditions at some point and it definitely is not something i will guarantee will work forever. (as this conversation continues, I'm trying to figure out how best to make init available without having the automatically created instance). 

You should only need to call authorize once. Use it to either initiate an oauth flow or to refresh an access token. Given it's multiple behaviors, I'm working on deprecating it. In the future, you'll use something like `initiateLogin` to kick off an oauth flow; if you already have an access token or refresh token, you'll simply start calling methods and the sdk will refresh the access token as appropriate. That's the future though, so I *think* something like the following will get you unblocked.

```javascript
const spark = ciscospark.init({
  config: {
    credentials: {
      // the next line is needed to make sure you get a refresh token; I fixed this a few times, but clearly there's still something not quite right with the merge algorithm for the various sources of config data
      clientType: `confidential`,
      oauth: {
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uri: redirectUri,
        scope,
      },
    },
  },
});

// The loaded event fires when all values stored in local storage have been loaded. That said, due to some race conditions, you may still need to rely on the `change:isAuthenticated` event.
spark.once(`loaded`, () => {
  // note that at some point in the future, isAuthenticated will be replaced by canAuthorize
  spark.listentoAndRun(spark, `change:isAuthenticated`, onAuthed)

  function onAuthed() {
    spark.stopListening(spark, `change:isAuthenticated, onAuthed);        
    if (spark.isAuthenticated) {
      // your app is ready
    }
    else {
      spark.authorize()
    }
  }
});
```

How are you deciding what client id/secret to use at runtime? Is it something your appserver is aware of? Could you dynamically generate the javascript file based on the id and secret you need? Unless you're already using a CDN, I think I can point you in the right direction for how to do that reasonably performantly.

**Comment by antoinelyset** [comment]
Thanks a lot. That's great support ! I will try this tomorrow soon.

Yes our server will be aware of the configuration. It's easier for us to prebuild the assets, and be able to use it on whatever environment we need (staging, production), with dynamic configuration. I think you should really let the possibility in SDK.

I don't like to compare but Google is doing just that (https://developers.google.com/api-client-library/javascript/start/start-js). It's more logical for to know exactly when the #init is done (we decide) and with which configuration.

**Comment by ianwremmel** [comment]
oh, so you're doing this at runtime more to separate your tooling than because you need multiple client ids in production? In that case, i recommend something like webpack's define plugin or babel's environment variables plugin. 

In any case, yes, i agree, we need a solution where this is all doable at runtime. We had an early design requirement that `const spark = require(\`ciscospark\`);` should give back an immediately usable object. That requirement has caused a lot of unexpected pain exactly like what you're dealing with. I've got some ideas on how to deal with this long term, but it's probably going to be a few weeks before I can get anything written beyond what I posted above. That said, I'm happy to continue troubleshooting if the code above doesn't quite work they way I think it does - this part of the api is in flux right now and I'm juggling two different implementations.

**Comment by antoinelyset** [comment]
Ok so after a bit (in fact a lot) of trying, I think there may be a race condition or another kind of problem.

After an OAuth workflow, I can see that there is data in the localStorage but if I call `isAuthenticated` it returns `false`, and if I recall `authorize()` it raise this exception : 

```
Unhandled promise rejection TypeError: Property 'authorization' must be of type state. Tried to set [object Object]
    at child.set (ampersand-state.js:214)
    at child.set (common.js:455)
    at eval (decorators.js:244)
    at wrapper (_createHybrid.js:87)
    at run (es6.promise.js:87)
    at eval (es6.promise.js:100)
    at MutationObserver.flush (_microtask.js:18)
```

**Comment by antoinelyset** [comment]
For more informations after trying with Webpack definePlugin, I can that the data in the localStorage, it now contains the refresh token and its expiration.

**Comment by RamithaW** [comment]
@antoinelyset any update from here? I am facing the same situation now.

**Comment by antoinelyset** [comment]
No sorry. I recommend you to use the "build time" configuration setting.

**Comment by RamithaW** [comment]
what do you mean by the build time configuration setting? do you mean to set the access token as an environment variable during build time instead? Is there any existing documentation that you can point me to perhaps?
Thanks!

**Comment by antoinelyset** [comment]
Yes, you can find more informations [here](https://ciscospark.github.io/spark-js-sdk/guides/browsers/) and if you are using Webpack, you should read this [section](https://webpack.js.org/plugins/define-plugin/)

**Comment by RamithaW** [comment]
thanks for the info!
