### ISSUE TITLE
Improve Documentation (Methods)

### ISSUE THREAD

**Issue by tahanson-cisco** [ciscospark/spark-js-sdk#82]
Some of the function examples, particularly the get(s) and list(s) seem complex for demonstration.  For those of us less familiar, it would be nice to see the results of the list at the end of the example.  Instead of creating new rooms to compare against, without actually seeing the returned boolean.  Why not:

ciscospark.rooms.list({max: 3})
      .then(function(rooms) {
        console.log(rooms.items);
        return rooms.items;
      });

**Comment by ianwremmel** [comment]
Hi @tahanson-cisco What do you mean by "the returned boolean"? Are you referring to the examples at https://ciscospark.github.io/spark-js-sdk/api/ or somewhere else? (given something you said in the other issue you posted, I want to make sure you don't have outdated docs from somewhere).

The examples use assertions instead of log statements so that they can be run through a test suite before being published (several of the early examples were broken for a while because they didn't keep up with the changing code base).

**Comment by tahanson-cisco** [comment]
Hello,  sorry again this appears to be a different docs issue.  I was looking at https://www.npmjs.com/package/ciscospark, which is what is linked from https://developer.ciscospark.com/sdk.html.

The list rooms example on that page has the line "return room.id === rooms.items[i].id;"  That was the boolean I was referring to.

Thank you for clearing that up.

**Comment by ianwremmel** [comment]
Closing as new documentation has been released.
